# Generated by Django 3.2.9 on 2021-12-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'verbose_name_plural': 'Bosses'},
        ),
        migrations.RemoveField(
            model_name='raid',
            name='bosses',
        ),
        migrations.AddField(
            model_name='raid',
            name='bosses',
            field=models.ManyToManyField(to='wings.Boss'),
        ),
        migrations.AlterField(
            model_name='raid',
            name='wing_num',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
