# Generated by Django 3.2.9 on 2021-12-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0002_auto_20211227_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='bosses',
        ),
        migrations.AddField(
            model_name='raid',
            name='bosses',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='wings.boss'),
        ),
    ]
