# Generated by Django 3.2.9 on 2021-12-27 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0003_auto_20211227_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='bosses',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='wings.boss'),
        ),
    ]
