# Generated by Django 3.2.9 on 2021-12-27 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0005_alter_raid_bosses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='bosses',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Boss', to='wings.boss'),
        ),
    ]
