# Generated by Django 3.2.9 on 2021-12-27 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0006_alter_raid_bosses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='wing_num',
        ),
        migrations.AddField(
            model_name='raid',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='raid',
            name='bosses',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wings.boss'),
        ),
    ]
