# Generated by Django 3.2.9 on 2021-12-27 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0007_auto_20211227_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='bosses',
        ),
        migrations.AddField(
            model_name='boss',
            name='raid_belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wings.raid'),
        ),
    ]
