# Generated by Django 3.2.9 on 2021-12-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0008_auto_20211227_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'ordering': ['-raid_name'], 'verbose_name_plural': 'Bosses'},
        ),
    ]
