# Generated by Django 3.2.9 on 2021-12-27 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0009_alter_boss_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boss',
            options={'verbose_name_plural': 'Bosses'},
        ),
        migrations.RemoveField(
            model_name='boss',
            name='raid_belong',
        ),
    ]
