# Generated by Django 3.2.9 on 2021-12-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0012_alter_boss_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boss',
            old_name='raid_name',
            new_name='raid_wing',
        ),
    ]
