# Generated by Django 3.2.9 on 2021-12-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0013_rename_raid_name_boss_raid_wing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='name',
            field=models.SlugField(),
        ),
    ]
