# Generated by Django 3.2.9 on 2021-12-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0014_alter_raid_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
