# Generated by Django 3.2.9 on 2021-12-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0015_alter_raid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='slug',
            field=models.SlugField(null=True, verbose_name=models.CharField(max_length=50)),
        ),
    ]
