# Generated by Django 3.2.9 on 2021-12-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0016_raid_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='slug',
        ),
        migrations.AlterField(
            model_name='raid',
            name='name',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
