# Generated by Django 3.2.9 on 2021-12-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0017_auto_20211231_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='raid',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name=models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='raid',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
