# Generated by Django 3.2.9 on 2021-12-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0027_alter_raid_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raid',
            name='slug',
        ),
    ]
