# Generated by Django 3.2.9 on 2021-12-31 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0037_alter_raid_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raid',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
